### ISSUE TITLE
question about extension to scene reconstruction

### ISSUE THREAD

**Issue by amiltonwong** [stevenygd/NFGP#1]
Hi, @stevenygd ,

Thanks for releasing the package. In your work, the NFGP is applied to 3D object instances. Is it possible to be applied to a more large-scale input, such as reconstructing an indoor room scene of sparse 3D points? 

Thanks~

**Comment by stevenygd** [comment]
That's a good question. Potentially this paper can be related: http://vladlen.info/papers/elastic-fragments.pdf.

Maybe one can try to replace the ARAP style loss in equation (4) with the continuous version developed in NFGP. That can make sense if the reconstruction output is represented with Neural Field(s).
