### ISSUE TITLE
Q about the implementation of I-resnet

### ISSUE THREAD

**Issue by ThibaultGROUEIX** [stevenygd/NFGP#2]
Hi @stevenygd,

Greatly enjoyed your paper !
I have two questions about your use of i-resnet for 3D deformations: 
1. I see in the original code of i-resnet that they set the spectral norm of each linear layer to be strictly inferior to 1, [here](https://github.com/jhjacobsen/invertible-resnet/blob/master/spectral_norm_fc.py#L93) , which I think is needed to apply fixed-point Banach to garantee invertibility. I don't see this scale parameter in your code, did you empirically found that you did not need it or did I miss something?
2. AFAIK,  fixed point Banach only works for linear layers whose output dim and input dim are the same, though I am no expert there. Can you kindly explain how you extended it to layers that do from 3 to 256 hidden dim? It's not clear to me how invertibility is maintained in this case.

Thanks a lot, and again congrats on the paper, it's very nice!
Thibault

**Comment by stevenygd** [comment]
Thibault - thanks for your interests!

1. I think if there is some non-linear layer with Lip const < 1 then it's invertible. But I agree that we should make sure the Lip cont is strictly < 1.  One way to do that is to multiply the output of the layer by a constant you desire.

2 The input and output of the residual block is the same dimension, which is the function we compute the Banach fixed point.

**Comment by ThibaultGROUEIX** [comment]
Thanks a lot @stevenygd
